config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :sale_items
  resources :orders

  resources :sessions, only: [:new, :create]
  delete 'sign_out' => 'sessions#destroy'
  resources :users

  post 'add_item_to_cart' => 'cookies#add_item_to_cart'
  post 'delete_item_from_cart' => 'cookies#delete_item_from_cart'
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :customer_name, presence: true
  validates :phone, presence: true
  validates :address, presence: true
end

app/models/sale_item.rb
class SaleItem < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_secure_password

  before_save { self.email = email.downcase }

  validates :name,
            length: { maximum: 50 }

  validates :email,
            presence: true,
            length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  validates :password,
            presence: true,
            length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :signed_in?, :require_signin

  def current_user
    return @current_user if @current_user
    @current_user ||= User.find(session[:user_id])
  end

  def require_signin
    if !signed_in?
      flash[:warning] = I18n.t 'session.warning'
      redirect_to new_session_path
    end
  end

  def signed_in?
    current_user
  end
end

app/controllers/cookies_controller.rb
require 'json'

class CookiesController < ApplicationController
  def add_item_to_cart
    redirect_to root_path unless params[:sale_item_id].present?
    cookies[:sale_item_ids] = JSON.generate({}) if cookies[:sale_item_ids].nil?
    cookies.permanent[:sale_item_ids] = JSON.generate(calculate_quanity(params[:quanity]))
    if params[:commit] == 'add'
      redirect_to action: 'show', controller: 'sale_items', id: params[:sale_item_id]
    else
      redirect_to :new_order
    end
  end

  def delete_item_from_cart
    sale_items_hash = JSON.parse(cookies[:sale_item_ids])
    sale_items_hash.delete(params[:delete_key])
    cookies.permanent[:sale_item_ids] = JSON.generate(sale_items_hash)
    redirect_to :new_order
  end

  private

  def encoded_key
    "#{params[:sale_item_id]}_#{params[:size]}"
  end

  def calculate_quanity(quanity)
    sale_items_hash = JSON.parse(cookies[:sale_item_ids])
    sale_items_hash[encoded_key] = 0 if sale_items_hash[encoded_key].nil?
    sale_items_hash[encoded_key] += quanity.to_i if sale_items_hash[encoded_key] < 10
    sale_items_hash
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @sale_items = SaleItem.all.map(&:decorate)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    if cookies[:sale_item_ids].nil?
      order_items_hash = {}
    else
      order_items_hash = JSON.parse(cookies[:sale_item_ids])
    end
    item_ids = order_items_hash.map { |order_item| order_item.first.to_i }
    order_item_groups = order_item_groups(item_ids)
    @order_items = generate_order_items(order_items_hash, order_item_groups)[0]
    @total = generate_order_items(order_items_hash, order_item_groups)[1]
  end

  def create
    @order = Order.new new_order_attributes
    if @order.save
      cookies.permanent[:sale_item_ids] = JSON.generate({})
      flash[:success] = I18n.t 'order.successfully'
      redirect_to :root
    else
      flash[:error] = I18n.t 'order.fail'
      redirect_to :new_order
    end
  end

  private

  def order_item_groups(item_ids)
    @order_item_groups ||= SaleItem.where(id: item_ids)
                             .select(:id, :name, :price, :image_url)
                             .group_by(&:id)
  end

  def generate_order_items(order_items_hash, order_item_groups)
    order_items = []
    total = 0

    order_items_hash.each do |key, value|
      size = key.split('_')[1]
      quanity = value
      item = order_item_groups[key.to_i].first
      price = item.price.to_i * quanity.to_i
      total += price

      order_items << {
        id: item.id,
        key: key,
        name: "#{item.name} Size #{size}",
        image_url: item.image_url,
        quanity: quanity,
        price: price
      }
    end

    [order_items, total]
  end

  def new_order_attributes
    {
      sale_items_code: generate_sale_items_code,
      customer_name: params[:name].strip,
      phone: params[:phone].strip,
      address: params[:address].strip,
      note: params[:note].strip,
      total_payment: params[:total]
    }
  end

  def generate_sale_items_code
    params[:order_items].map do |order_item|
      "#{order_item[:key]}_#{order_item[:quanity]}"
    end.join(',')
  end
end

app/controllers/sale_items_controller.rb
class SaleItemsController < ApplicationController
  def show
    @sale_item = sale_item.decorate
  end

  private

  def sale_item
    @sale_item = SaleItem.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user
      if @user.authenticate(params[:password])
        flash.now[:success] = I18n.t 'session.signed_in'
        session[:user_id] = @user.id
        redirect_to root_path
      else
        flash.now[:error] = I18n.t 'session.wrong_password'
        render 'new'
      end
    else
      flash.now[:error] = I18n.t 'session.not_found'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, flash: {info: 'Signed out'}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new new_user_attributes
    if @user.save
      flash[:success] = I18n.t 'user.successfully'
      session[:user_id] = @user.id
      redirect_to :root
    else
      render :new
    end
  end

  private

  def new_user_attributes
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
require 'json'

module ApplicationHelper
  def cart_is_not_empty?
    JSON.parse(cookies[:sale_item_ids]).present? if !cookies[:sale_item_ids].nil?
  end

  def semantic_class_for flash_type
    { success: 'positive message', error: 'negative message', notice: 'warning message', info: 'info message'}[flash_type.to_sym]
  end

  def flash_messages(opts = {})
    flash.map do |msg_type, message|
      content_tag(:div, message, class: "ui #{semantic_class_for(msg_type)}") do
        content_tag(:i, ''.html_safe, class: 'close icon', data: {dismiss: 'message'}) + content_tag(:div, message)
      end
    end.join.html_safe
  end
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
  def vnd_price(money)
    Formatters::MoneyFormatter.vnd_formatter(money)
  end
end

app/helpers/sale_items_helper.rb
module SaleItemsHelper
end

app/views/home/_sale_item_card.html.erb
<div class="card home-card">
  <a href="<%= sale_item_path(id: sale_item) %>">
    <%= image_tag(sale_item.image_url , class: "ui image") %>
  </a>
  <div class="content">
    <div class="header home-item-name">
    <%= sale_item.name %>
    </div>
    <div class="description home-item-detail">
    <%= sale_item.simple_first_sentence  %>
    </div>
  </div>
  <div class="home-item-price">
    <span class="right floated">
    <%= sale_item.vnd_price  %>
    </span>
  </div>
</div>

app/views/home/index.html.erb
<div class="ui container">
  <%= flash_messages %>
</div>
<%= render "layouts/quote" %>
<div class="ui container">
  <div class="ui four cards">
    <% @sale_items.each do |sale_item| %>
      <%= render partial: "sale_item_card", locals: { sale_item: sale_item } %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer-top-space">
</div>
<div class="ui black inverted vertical segment">
  <div class="infooter-space"></div>
  <div class="ui grid">
    <div class="two wide column">
    </div>
    <div class="six wide column">
      <div class="footer-contact">
        <i class="facebook large icon"></i>
        <span>Contact us on facebook</span>
      </div>
      <div class="footer-contact">
        <i class="instagram large icon"></i>
        <span>Contact us on instagram</span>
      </div>
    </div>
    <div class="six wide column">
    </div>
    <div class="two wide column">
    </div>
  </div>
  <div class="ui center aligned container">
    <div class="ui inverted section divider"></div>
    <h1 class="brand-name">P</h1>
  </div>
  <div class="infooter-space"></div>
</div>

app/views/layouts/_navbar.html.erb
<div class="ui large borderless inverted menu no-radius">
  <div class="ui container">
    <a class="item" href="<%= root_path %>">
      <h1 class="brand-name">Pierro</h1>
    </a>
    <div class="right menu">
      <% if cart_is_not_empty? %>
      <span id="red-note-baby"></span>
      <% end %>
      <a class="item" href="<%= new_order_path %>">
        <i class="large cart icon"></i>
      </a>
    </div>
  </div>
</div>

app/views/layouts/_quote.html.erb
<div class="ui container">
  <div class="home-quote" id="quote">
    <p>
      “Fashion is not necessarily about labels. It’s not about brands. It’s about something else that comes from within you.” — <strong>Ralph Lauren</strong>
    </p>
  </div>
</div>

<script>
  $('#quote').transition({
    animation : 'scale in',
    duration  : '1000ms',
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pierro</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/orders/_checkout_form.html.erb
<div class="ui grid">
  <div class="four wide column">
  </div>
  <div class="eight wide column">
    <%= form_tag(orders_path(order_items: order_items, total: total), method: :post, class: 'ui form') do %>
      <div class="field">
        <%= text_field_tag('name', nil, placeholder: 'Tên của bạn', size: 30) %>
      </div>
      <div class="field">
        <%= text_field_tag('phone', nil, placeholder: 'Số điẹn thoại', size: 20) %>
      </div>
      <div class="field">
        <%= text_field_tag('address', nil, placeholder: 'Địa chỉ giao hàng', size: 120) %>
      </div>
      <div class="field">
        <%= text_area_tag('note', nil, placeholder: 'Ghi chú', rows: '3', size: 200) %>
      </div>
      <button type="submit" name="commit" value="order" id="cart-btn" class="ui fluid green labeled icon button">
        <i class="cart icon"></i>
        Đặt hàng
      </button>
    <% end %>
  </div>
  <div class="four wide column">
  </div>
</div>

app/views/orders/_checkout_items.html.erb
<table class="ui single line table">
  <thead class="item-font-size">
    <tr>
      <th>Tên sản phẩm</th>
      <th>Số lượng</th>
      <th>Giá tiền</th>
      <th></th>
    </tr>
  </thead>
  <tbody class="item-font-size">
    <% order_items.each do |order_item| %>
    <tr>
      <td>
        <img class="ui middle aligned tiny image" src="<%= order_item[:image_url] %>">
        <span><%= order_item[:name] %></span>
      </td>
      <td>
        <p><%= order_item[:quanity] %></p>
      </td>
      <td>
        <p><%= vnd_price(order_item[:price]) %></p>
      </td>
      <td>
        <%= link_to 'Remove', delete_item_from_cart_path(delete_key: order_item[:key]), method: :post %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="total-price">
  <p>Tổng cộng: <%= vnd_price(total) %></p>
</div>

app/views/orders/new.html.erb
<div class="ui container quicksand-font">
  <%= flash_messages %>
  <% if @order_items.size > 0 %>
    <%= render partial: "checkout_items", locals: { order_items: @order_items, total: @total } %>
    <%= render partial: "checkout_form", locals: { order_items: @order_items, total: @total } %>
  <% else %>
    <div class="ui warning message">
      <div class="quicksand-font">
        Giỏ hàng của bạn hiện không có sản phẩm nào
      </div>
    </div>
  <% end %>
</div>

app/views/sale_items/show.html.erb
<div class="sale-item-top-space">
</div>
<div class="ui container">
  <div class="ui grid">
    <div class="six wide column">
      <div class="ui fluid card">
          <div class="image">
            <img src="<%= @sale_item.image_url %>">
          </div>
        </div>
    </div>
    <div class="ten wide column">
      <h2 class="sale-item-name"><%= @sale_item.name %></h2>
      <div class="detail-content">
        <div class="sale-item-detail">
          <%= simple_format(@sale_item.description) %>
        </div>
        <p class="sale-item-price"><%= @sale_item.vnd_price %></p>
        <%= form_tag(add_item_to_cart_path(sale_item_id: @sale_item.id), method: :post) do %>
          <div class="sale-item-dropdown">
            <span>Số lượng: </span>
            <%= select_tag 'quanity', options_for_select((1..10).to_a), class: 'ui dropdown' %>
          </div>
          <div class="sale-item-dropdown">
            <span>Size: </span>
            <%= select_tag 'size', options_for_select(@sale_item.sizes_array), class: 'ui dropdown' %>
          </div>
          <button type="submit" name="commit" value="check" id="cart-btn" class="ui large green button">
            Mua ngay
          </button>
          <button type="submit" name="commit" value="add" id="cart-btn" class="ui large blue button">
            Thêm vào giỏ hàng
          </button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="ui grid">
  <div class="four wide column">
  </div>
  <div class="eight wide column">
    <div class="ui form">
      <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
          <div class="ui yellow message"><%= @user.errors.full_messages.uniq.to_sentence %></div>
        <% end %>
        <div class="field">
          <%= f.label I18n.t 'user.name' %>
          <%= f.text_field :name, placeholder: 'Tên' %>
        </div>
        <div class="field">
          <%= f.label :email %>
          <%= f.text_field :email, placeholder: 'Email' %>
        </div>
        <div class="field">
          <%= f.label I18n.t 'user.password' %>
          <%= f.password_field :password, placeholder: 'Mật khẩu phải có ít nhất 6 ký tự' %>
        </div>
        <%= f.submit I18n.t('user.register'), class: 'ui large green button' %>
      <% end %>
    </div>
  </div>
  <div class="four wide column">
  </div>
</div>